#!/usr/bin/env python
"""Rerank no-anchor scheduler rows with a median proxy-reviewer ensemble.

This is a Deli AutoResearch-style referee layer: candidate rows are generated by
other no-anchor workers, while this script only arbitrates them with several
previously-trained full-IDF1 proxy models.  GT labels are not used here; the
models may have been trained from completed full-score outcomes, but production
selection uses only candidate metadata and no-anchor features.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from kit.no_anchor_fullscore_scheduler import (
    _as_float,
    _family_key,
    _model_score,
    _normalize_row,
    _oracle_or_gt_selection_reason,
    _select,
    _write_csv,
)


ROW_KEYS = ("selected", "top", "rows", "results", "top_rows", "full_rows", "top_full_rows")


def _load_candidate_rows(path: Path) -> list[dict[str, Any]]:
    if path.suffix.lower() == ".csv":
        with path.open(newline="") as handle:
            rows = [dict(row) for row in csv.DictReader(handle)]
    else:
        data = json.loads(path.read_text())
        rows = []
        if isinstance(data, list):
            rows = [row for row in data if isinstance(row, dict)]
        elif isinstance(data, dict):
            for key in ROW_KEYS:
                value = data.get(key)
                if isinstance(value, list):
                    rows.extend(row for row in value if isinstance(row, dict))
            if not rows and any(key in data for key in ("pair_f1", "tracklet_pair_f1", "predicted_full_idf1")):
                rows.append(data)
    out: list[dict[str, Any]] = []
    for rank, row in enumerate(rows, start=1):
        out.append({"_ensemble_source_file": str(path), "_ensemble_source_rank": rank, **row})
    return out


def _load_rows(paths: list[str]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for text in paths:
        matches = sorted(Path().glob(text)) if any(ch in text for ch in "*?[]") else [Path(text)]
        for path in matches:
            if path.is_file():
                out.extend(_load_candidate_rows(path))
    return out


def _load_models(paths: list[str]) -> list[tuple[str, dict[str, Any]]]:
    models: list[tuple[str, dict[str, Any]]] = []
    for text in paths:
        matches = sorted(Path().glob(text)) if any(ch in text for ch in "*?[]") else [Path(text)]
        for path in matches:
            if not path.is_file():
                continue
            data = json.loads(path.read_text())
            if isinstance(data, dict) and data.get("columns") and data.get("coef"):
                models.append((str(path), data))
    return models


def _reviewer_scores(row: dict[str, Any], models: list[tuple[str, dict[str, Any]]]) -> list[dict[str, Any]]:
    scores: list[dict[str, Any]] = []
    for name, model in models:
        score = _model_score(row, model)
        if score is None:
            continue
        scores.append({"model": name, "score": float(score)})
    if not scores:
        fallback = _as_float(row.get("predicted_full_idf1"), _as_float(row.get("learned_proxy_full_idf1")))
        if fallback is not None:
            scores.append({"model": "fallback_row_predicted_full", "score": float(fallback)})
    return scores


def _eligible(row: dict[str, Any], args: argparse.Namespace) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    if _oracle_or_gt_selection_reason(row):
        reasons.append(str(_oracle_or_gt_selection_reason(row)))
    if _as_float(row.get("pair_f1_norm"), 0.0) < float(args.min_pair_f1):
        reasons.append("low_pair_f1")
    if _as_float(row.get("pair_precision_norm"), 0.0) < float(args.min_pair_precision):
        reasons.append("low_pair_precision")
    if _as_float(row.get("pair_recall_norm"), 0.0) < float(args.min_pair_recall):
        reasons.append("low_pair_recall")
    delivery = _as_float(row.get("delivery_tracklets_min_norm"))
    if delivery is not None and delivery < float(args.min_delivery_tracklets):
        reasons.append("low_delivery")
    if _as_float(row.get("ensemble_median_full"), 0.0) < float(args.min_median_full):
        reasons.append("low_ensemble_median")
    if _as_float(row.get("ensemble_min_full"), 0.0) < float(args.min_reviewer_min_full):
        reasons.append("low_reviewer_min")
    if int(row.get("ensemble_above_current_count", 0)) < int(args.min_reviewers_above_current):
        reasons.append("too_few_reviewers_above_current")
    if bool(row.get("is_full_scored_norm")) and not bool(args.include_full_scored):
        reasons.append("already_full_scored")
    known = _as_float(row.get("known_full_idf1_norm"))
    if known is not None and known < float(args.current_best_full_idf1):
        reasons.append("known_below_current_best")
    return not reasons, reasons


def _normalize_with_ensemble(
    row: dict[str, Any],
    models: list[tuple[str, dict[str, Any]]],
    *,
    current_best: float,
    uncertainty_weight: float,
) -> dict[str, Any]:
    base = _normalize_row(row, None)
    scores = _reviewer_scores(row, models)
    values = np.asarray([item["score"] for item in scores], dtype=np.float64)
    if len(values):
        median = float(np.median(values))
        mean = float(np.mean(values))
        minimum = float(np.min(values))
        maximum = float(np.max(values))
        std = float(np.std(values))
    else:
        median = mean = minimum = maximum = std = float(base["predicted_full_idf1"])
    risk = _as_float(base.get("scheduler_risk_penalty"), 0.0) or 0.0
    above = int(np.sum(values > float(current_best))) if len(values) else int(median > current_best)
    family = _family_key(base)
    ensemble_score = median - float(uncertainty_weight) * std - risk
    return {
        **base,
        "scheduler_family": family,
        "predicted_full_idf1": median,
        "scheduler_score": float(ensemble_score),
        "ensemble_median_full": median,
        "ensemble_mean_full": mean,
        "ensemble_min_full": minimum,
        "ensemble_max_full": maximum,
        "ensemble_std_full": std,
        "ensemble_above_current_count": above,
        "ensemble_reviewer_count": len(scores),
        "ensemble_reviewer_scores": scores,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--candidate", action="append", default=[])
    ap.add_argument("--proxy-model-json", action="append", default=[])
    ap.add_argument("--current-best-full-idf1", type=float, default=0.655240)
    ap.add_argument("--min-pair-f1", type=float, default=0.70)
    ap.add_argument("--min-pair-precision", type=float, default=0.70)
    ap.add_argument("--min-pair-recall", type=float, default=0.70)
    ap.add_argument("--min-delivery-tracklets", type=float, default=7000.0)
    ap.add_argument("--min-median-full", type=float, default=0.655240)
    ap.add_argument("--min-reviewer-min-full", type=float, default=0.0)
    ap.add_argument("--min-reviewers-above-current", type=int, default=2)
    ap.add_argument("--uncertainty-weight", type=float, default=0.5)
    ap.add_argument("--include-full-scored", action="store_true")
    ap.add_argument("--max-per-mode", type=int, default=0)
    ap.add_argument("--top-n", type=int, default=8)
    ap.add_argument("--json", required=True)
    ap.add_argument("--csv", default="")
    ap.add_argument("--md", default="")
    args = ap.parse_args()

    if not args.candidate:
        ap.error("--candidate is required")
    if not args.proxy_model_json:
        ap.error("--proxy-model-json is required")
    models = _load_models(args.proxy_model_json)
    if not models:
        ap.error("no usable proxy models found")

    raw = _load_rows(args.candidate)
    normalized = [
        _normalize_with_ensemble(
            row,
            models,
            current_best=float(args.current_best_full_idf1),
            uncertainty_weight=float(args.uncertainty_weight),
        )
        for row in raw
    ]
    eligible: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    for row in normalized:
        ok, reasons = _eligible(row, args)
        row["scheduler_exclusion_reasons"] = reasons
        if ok:
            eligible.append(row)
        else:
            rejected.append(row)
    selected = _select(eligible, args)

    result = {
        "input_candidates": args.candidate,
        "proxy_models": [name for name, _ in models],
        "raw_count": len(raw),
        "eligible_count": len(eligible),
        "rejected_count": len(rejected),
        "selected": selected,
        "top_rejected": sorted(rejected, key=lambda item: float(item["scheduler_score"]), reverse=True)[:20],
        "current_best_full_idf1": float(args.current_best_full_idf1),
        "min_median_full": float(args.min_median_full),
        "min_reviewer_min_full": float(args.min_reviewer_min_full),
        "min_reviewers_above_current": int(args.min_reviewers_above_current),
        "uncertainty_weight": float(args.uncertainty_weight),
        "uses_anchors": False,
        "uses_gt_for_training_or_anchors": False,
        "uses_gt_for_evaluation_only": False,
        "note": "Median proxy-reviewer rerank only; selected rows still require canonical DS1 full scoring.",
    }
    Path(args.json).parent.mkdir(parents=True, exist_ok=True)
    Path(args.json).write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    if args.csv:
        _write_csv(args.csv, selected)
    if args.md:
        lines = [
            "# No-Anchor Proxy-Reviewer Ensemble Scheduler",
            "",
            f"- raw candidates: `{len(raw)}`",
            f"- eligible: `{len(eligible)}`",
            f"- rejected: `{len(rejected)}`",
            f"- proxy reviewers: `{len(models)}`",
            f"- current best full IDF1: `{args.current_best_full_idf1:.6f}`",
            f"- min median full: `{args.min_median_full:.6f}`",
            f"- min reviewers above current: `{args.min_reviewers_above_current}`",
            "",
            "## Selected",
            "",
            "| rank | ensemble | median | min | max | std | above current | pair F1 | family |",
            "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
        ]
        for rank, row in enumerate(selected, start=1):
            lines.append(
                f"| {rank} | `{row['scheduler_score']:.6f}` | `{row['ensemble_median_full']:.6f}` | "
                f"`{row['ensemble_min_full']:.6f}` | `{row['ensemble_max_full']:.6f}` | "
                f"`{row['ensemble_std_full']:.6f}` | `{row['ensemble_above_current_count']}` | "
                f"`{row['pair_f1_norm']:.6f}` | `{row['scheduler_family']}` |"
            )
        lines.extend(["", "## Proxy Reviewers", ""])
        for name, _ in models:
            lines.append(f"- `{name}`")
        Path(args.md).parent.mkdir(parents=True, exist_ok=True)
        Path(args.md).write_text("\n".join(lines) + "\n")
    print(json.dumps({"raw": len(raw), "eligible": len(eligible), "selected": len(selected)}, sort_keys=True))


if __name__ == "__main__":
    main()
